openapi: 3.0.0
info:
  title: EC Shop
  description: EC Shop API
  version: 1.0.0
paths:
  /v1/products:
    get:
      description: 全商品を取得
      parameters:
        - name: limit
          in: query
          description: 取得する商品数
          required: false
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
        - name: offset
          in: query
          description: 取得する商品のオフセット
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductVariants'
                  total:
                    type: integer
                    format: int64
    post:
      description: 商品を登録
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Sample Product"
                  maxLength: 255
              required:
                - name
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prouct'
  /v1/login:
    post:
      description: ログイン
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "hoge@example.com"
                  format: email
                password:
                  type: string
                  example: "password"
              required:
                - email
                - password
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6ImhvbWVAZXhhbXBsZS5jb20iLCJpYXQiOjE1MTYyMzkwMjJ9.7J4z"
components:
  schemas:
    Prouct:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    ProductVariants:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        validations:
          type: array
          items:
            $ref: '#/components/schemas/Variant'
    Variant:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: integer