# go-arch-lint の設定ファイル
# https://github.com/fe3dback/go-arch-lint

version: 3

workdir: .

allow:
  deepScan: false # よくわからないから一旦false

# 除外するファイルのパターン
excludeFiles:
  - "^.*_test\\.go$"
  - "^.*\/test\/.*$"
  - "^.*_mock\\.go$"
  - "^.*\/tmp\/.*$"
  - "^.*\/gen\/.*$"
  - "^.*\/mock\/.*$"
  - "^.*\/mock\/.*$"
  - "^.*\/cmd\/grpc\/*.go"

exclude:
  - cmd/grpc
  - handler/rpc

components:
  main: { in: cmd/server }
  genapi: { in: gen/api }
  controller: { in: handler/controller }
  registry: { in: registry }
  input: { in: domain/dto/input }
  output: { in: domain/dto/output }
  usecase: { in: usecase }
  repository: { in: domain/repository }
  model: { in: domain/model }
  weberror: { in: library/weberrors }
  # infra層
  db: { in: infra/db }
  dao: { in: infra/dao/** }

vendors:
  echo:
    in:
      - github.com/labstack/echo/*
  zap: { in: go.uber.org/zap }
  gorm: { in: gorm.io/** }

# どのパッケージからも呼び出せるパッケージ名
commonComponents:
  - weberror

# どのパッケージからも呼び出せるベンダーパッケージ名
commonVendors:
  - zap

deps:
  main:
    anyVendorDeps: true
    mayDependOn:
      - genapi
      - controller
      - registry

  controller:
    mayDependOn:
      - registry
      - genapi
      - input
      - output
      - usecase
    canUse:
      - echo

  usecase:
    mayDependOn:
      - input
      - output
      - repository
      - model

  output:
    mayDependOn:
      - model

  repository:
    mayDependOn:
      - model

  registry:
    mayDependOn:
      - repository
      - db
      - dao
  
  db:
    anyVendorDeps: true
    anyProjectDeps: true
  
  dao:
    anyVendorDeps: true
    anyProjectDeps: true
