version: "3"
services:
  ec-server:
    build:
      context: ./docker/go
      dockerfile: Dockerfile
    tty: true # コンテナの起動永続化
    volumes:
      - ./app:/go/src/app
    ports:
      - 1323:1323
    environment:
      TZ: 'Asia/Tokyo'
  ec-db:
    image: mysql:8.3.0
    # restart: always
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      TZ: "Asia/Tokyo"
      MYSQL_DATABASE: "ec"
